# Generated by Django 2.2.10 on 2020-02-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=50)),
                ('headquater', models.CharField(max_length=100)),
                ('founder', models.CharField(max_length=40)),
            ],
        ),
    ]
